name: aws-lambda

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.X'

      - name: Install dependencies
        working-directory: aws-lambda
        run: npm run prep

      - name: Build Typescript
        working-directory: aws-lambda
        run: npm run build

      - name: Install AWS CDK Globally
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Bootstrap (if needed)
        working-directory: aws-lambda
        run: cdk bootstrap

      - name: CDK Deploy
        working-directory: aws-lambda
        run: cdk deploy --require-approval never