name: express-lambda

on:
  pull_request:
    branches: [main, master]
    types : [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: express-lambda

jobs:
  deploy:
    name: express-api
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.X

      - name: install AWS CDK Globally
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Install Dependencies
        run: npm run prep

      - name: build Project
        run: npm run build

      - name: Conditional CDK Bootstrap
        run: |
          if aws cloudformation describe-stacks --stack-name CDKToolkit >/dev/null 2>&1; then
            echo "CDK already bootstrapped. Skipping bootstrap..."
          else
            echo "CDK not bootstrapped. Running bootstrap..."
            npm run bootstrap
          fi


      - name: CDK Deploy
        run: npm run deploy
